import json

EN_DEFS = [
  'Account means a unique account created for you to access our Service or parts of our Service.',
  'Affiliate means an entity that controls, is controlled by, or is under common control with a party.',
  'Company (referred to as "the Company", "We", "Us" or "Our" in this Agreement) refers to Case Settlement Now (also known as Accident Help Now).',
  'Cookies are small files that are placed on your computer, mobile device, or any other device by a website.',
  'Country refers to: United States.',
  'Device means any device that can access the Service, such as a computer, cell phone, or digital tablet.',
  'Personal Data is any information relating to an identified or identifiable individual.',
  'Service refers to the Website.',
  'Service Provider means any natural or legal person who processes data on behalf of the Company.',
  'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.',
  'Website refers to Case Settlement Now (also known as Accident Help Now), accessible from https://casesettlementnow.com/',
  'You mean the individual accessing or using the Service, or the company or other legal entity on whose behalf such individual accesses or uses the Service.',
]

CA_DEFS = list(EN_DEFS)
CA_DEFS[4] = 'Country refers to: California, United States.'

EN_PERSONAL_LIST = [
  'Email address', 'Name and surname', 'Phone number',
  'Address, State, Province, ZIP/Postal Code, City', 'Usage Data',
]

EN_USE_LIST = [
  'To provide and maintain our Service',
  'To manage your account',
  'To contact you by email, phone calls, or SMS',
  'To provide news, updates, and special offers',
  'To manage your requests',
  'For business transfers and commercial purposes',
]

def build_en():
  return {
    'title': 'Privacy Policy',
    'lastUpdated': 'Last updated: November 13, 2024',
    'intro': 'This Privacy Policy describes Our policies and procedures regarding the collection, use, and disclosure of Your information when you use the Service and informs you about Your privacy rights and how the law protects you.\n\nWe use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.',
    's1Title': 'Interpretation and Definitions',
    's1InterpTitle': 'Interpretation',
    's1InterpBody': 'Words whose initial letter is capitalized have meanings defined under the following conditions. The following definitions will have the same meaning regardless of whether they appear in singular or plural.',
    's1DefsTitle': 'Definitions',
    's1DefsIntro': 'For the purposes of this Privacy Policy:',
    's1Defs': EN_DEFS,
    's2Title': 'Collection and Use of Your Personal Data',
    's2TypesTitle': 'Types of Data Collected',
    's2PersonalTitle': 'Personal Data',
    's2PersonalBody': 'While using our Service, we may ask you to provide certain personally identifiable information including:',
    's2PersonalList': EN_PERSONAL_LIST,
    's2UsageTitle': 'Usage Data',
    's2UsageBody': 'Usage Data is automatically collected when you use the Service and may include your IP address, browser type, browser version, pages visited, time spent on pages, device identifiers, and diagnostic data.',
    's2CookiesTitle': 'Tracking Technologies and Cookies',
    's2CookiesBody': 'We use cookies and similar tracking technologies to monitor activity on our Service and store certain information. We use both session and persistent cookies for various purposes.',
    's2UseTitle': 'Use of Your Personal Data',
    's2UseIntro': 'The Company may use Personal Data:',
    's2UseList': EN_USE_LIST,
    's3Title': 'Retention of Your Personal Data',
    's3Body': 'The Company will retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy.',
    's4Title': 'Security of Your Personal Data',
    's4Body': 'The security of your personal data is important to us; however, no method of transmission over the Internet or electronic storage is 100% secure.',
    's5Title': "Children's Privacy",
    's5Body': 'Our Service is not directed to children under the age of 13. We do not knowingly collect personally identifiable information from children under the age of 13.',
    's6Title': 'Changes to this Privacy Policy',
    's6Body': 'We may update this Privacy Policy from time to time. Any changes will be posted on this page.',
    's7Title': 'Contact Us',
    's7Body': 'If you have any questions about this Privacy Policy, you can contact us at:',
    's7Email': 'Email: remove@lc.casesettlementnow.com',
    's7Phone': 'Phone Number: +17704049406',
    'sCaliforniaTitle': '',
    'sCaliforniaBody': '',
    'close': 'Close',
  }

def build_es():
  return {
    'title': 'Política de Privacidad',
    'lastUpdated': 'Última actualización: 13 de noviembre de 2024',
    'intro': 'Esta Política de Privacidad describe nuestras políticas y procedimientos con respecto a la recopilación, uso y divulgación de su información cuando utiliza el Servicio, e informa sobre sus derechos de privacidad y cómo la ley le protege.\n\nUtilizamos sus datos personales para proporcionar y mejorar el Servicio. Al utilizar el Servicio, usted acepta la recopilación y el uso de información de acuerdo con esta Política de Privacidad.',
    's1Title': 'Interpretación y Definiciones',
    's1InterpTitle': 'Interpretación',
    's1InterpBody': 'Las palabras cuya letra inicial está en mayúscula tienen significados definidos bajo las siguientes condiciones. Las siguientes definiciones tendrán el mismo significado independientemente de si aparecen en singular o plural.',
    's1DefsTitle': 'Definiciones',
    's1DefsIntro': 'A los efectos de esta Política de Privacidad:',
    's1Defs': [
      'Cuenta significa una cuenta única creada para que usted acceda a nuestro Servicio o partes del mismo.',
      'Afiliado significa una entidad que controla, es controlada por, o está bajo control común con una parte.',
      'Empresa (referida como "la Empresa", "Nosotros", "Nos" o "Nuestro" en este Acuerdo) se refiere a Case Settlement Now (también conocido como Accident Help Now).',
      'Las Cookies son pequeños archivos que se colocan en su computadora, dispositivo móvil o cualquier otro dispositivo por un sitio web.',
      'País se refiere a: Estados Unidos.',
      'Dispositivo significa cualquier dispositivo que puede acceder al Servicio, como una computadora, teléfono celular o tableta digital.',
      'Datos Personales son cualquier información relacionada con un individuo identificado o identificable.',
      'Servicio se refiere al Sitio Web.',
      'Proveedor de Servicios significa cualquier persona natural o jurídica que procesa datos en nombre de la Empresa.',
      'Datos de Uso se refieren a datos recopilados automáticamente, ya sea generados por el uso del Servicio o desde la propia infraestructura del Servicio.',
      'Sitio Web se refiere a Case Settlement Now (también conocido como Accident Help Now), accesible desde https://casesettlementnow.com/',
      'Usted significa el individuo que accede o usa el Servicio, o la empresa u otra entidad legal en cuyo nombre dicho individuo accede o usa el Servicio.',
    ],
    's2Title': 'Recopilación y Uso de Sus Datos Personales',
    's2TypesTitle': 'Tipos de Datos Recopilados',
    's2PersonalTitle': 'Datos Personales',
    's2PersonalBody': 'Mientras usa nuestro Servicio, podemos pedirle que nos proporcione cierta información de identificación personal, incluyendo:',
    's2PersonalList': [
      'Dirección de correo electrónico',
      'Nombre y apellido',
      'Número de teléfono',
      'Dirección, Estado, Provincia, Código Postal, Ciudad',
      'Datos de Uso',
    ],
    's2UsageTitle': 'Datos de Uso',
    's2UsageBody': 'Los Datos de Uso se recopilan automáticamente cuando usa el Servicio y pueden incluir su dirección IP, tipo de navegador, versión del navegador, páginas visitadas, tiempo en páginas, identificadores de dispositivos y datos de diagnóstico.',
    's2CookiesTitle': 'Tecnologías de Seguimiento y Cookies',
    's2CookiesBody': 'Utilizamos cookies y tecnologías de seguimiento similares para monitorear la actividad en nuestro Servicio y almacenar cierta información. Utilizamos tanto cookies de sesión como persistentes para diversos propósitos.',
    's2UseTitle': 'Uso de Sus Datos Personales',
    's2UseIntro': 'La Empresa puede usar los Datos Personales:',
    's2UseList': [
      'Para proporcionar y mantener nuestro Servicio',
      'Para administrar su cuenta',
      'Para contactarle por correo electrónico, llamadas telefónicas o SMS',
      'Para proporcionarle noticias, actualizaciones y ofertas especiales',
      'Para gestionar sus solicitudes',
      'Para transferencias comerciales y propósitos comerciales',
    ],
    's3Title': 'Retención de Sus Datos Personales',
    's3Body': 'La Empresa conservará sus Datos Personales solo durante el tiempo necesario para los fines establecidos en esta Política de Privacidad.',
    's4Title': 'Seguridad de Sus Datos Personales',
    's4Body': 'La seguridad de sus datos personales es importante para nosotros; sin embargo, ningún método de transmisión por Internet o almacenamiento electrónico es 100% seguro.',
    's5Title': 'Privacidad de los Niños',
    's5Body': 'Nuestro Servicio no está dirigido a menores de 13 años. No recopilamos conscientemente información de identificación personal de menores de 13 años.',
    's6Title': 'Cambios en esta Política de Privacidad',
    's6Body': 'Podemos actualizar esta Política de Privacidad de vez en cuando. Cualquier cambio se publicará en esta página.',
    's7Title': 'Contáctenos',
    's7Body': 'Si tiene alguna pregunta sobre esta Política de Privacidad, puede contactarnos en:',
    's7Email': 'Correo electrónico: remove@lc.casesettlementnow.com',
    's7Phone': 'Número de teléfono: +17704049406',
    'sCaliforniaTitle': '',
    'sCaliforniaBody': '',
    'close': 'Cerrar',
  }

def build_ca():
  p = build_en()
  p['s1Defs'] = CA_DEFS
  p['sCaliforniaTitle'] = 'California Privacy Rights'
  p['sCaliforniaBody'] = 'California residents have the right to request deletion of their personal data in accordance with the California Consumer Privacy Act (CCPA), subject to applicable legal exceptions.'
  return p

updates = {'en': build_en(), 'es': build_es(), 'ca': build_ca()}

for locale, pp in updates.items():
  path = f'd:/lander/messages/{locale}.json'
  with open(path, encoding='utf-8') as f:
    data = json.load(f)
  data['privacyPolicy'] = pp
  with open(path, 'wb') as f:
    f.write(json.dumps(data, ensure_ascii=False, indent=2).encode('utf-8'))
  print(f'{locale}: done')
